-- Add new input actions:
INSERT OR REPLACE INTO "InputActions" VALUES ('ExtraHotkeysPillageOrRepair','LOC_TPT_UNITCOMMAND_PROMOTE_OR_REPAIR_NAME','LOC_TPT_UNITCOMMAND_PROMOTE_OR_REPAIR_DESC','UNIT','World','PC');
INSERT OR REPLACE INTO "InputActions" VALUES ('ExtraHotkeysUpgrade','LOC_UNITOPERATION_UPGRADE_DESCRIPTION','LOC_UNITOPERATION_UPGRADE_DESCRIPTION','UNIT','World','PC');
INSERT OR REPLACE INTO "InputActions" VALUES ('ExtraHotkeysPromote','LOC_HUD_UNIT_CHOOSE_PROMOTION_TEXT','LOC_HUD_UNIT_CHOOSE_PROMOTION_TEXT','UNIT','World','PC');
INSERT OR REPLACE INTO "InputActions" VALUES ('ExtraHotkeysUnitCancel','LOC_UNITCOMMAND_STOP_AUTOMATION_DESCRIPTION','LOC_UNITCOMMAND_STOP_AUTOMATION_DESCRIPTION','UNIT','World','PC');

INSERT OR REPLACE INTO "InputActionDefaultGestures" VALUES ('ExtraHotkeysPillageOrRepair',0,'KBMouse','LOC_OPTIONS_KEY_SHIFT+LOC_OPTIONS_KEY_P');
INSERT OR REPLACE INTO "InputActionDefaultGestures" VALUES ('ExtraHotkeysUpgrade',0,'KBMouse','LOC_OPTIONS_KEY_SHIFT+LOC_OPTIONS_KEY_E');
INSERT OR REPLACE INTO "InputActionDefaultGestures" VALUES ('ExtraHotkeysPromote',0,'KBMouse','LOC_OPTIONS_KEY_SHIFT+LOC_OPTIONS_KEY_G');
INSERT OR REPLACE INTO "InputActionDefaultGestures" VALUES ('ExtraHotkeysUnitCancel',0,'KBMouse','LOC_OPTIONS_KEY_SHIFT+LOC_OPTIONS_KEY_S');

