INSERT INTO Modifiers(ModifierId, ModifierType) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');

INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','DistrictType','DISTRICT_INDUSTRIAL_ZONE'),
	('BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION','Amount','100');

INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_MODIFIER_BOOST_INDUSTRIAL_ZONE_PRODUCTION');

UPDATE ModifierStrings SET Text='LOC_ABILITY_LINCOLN_MELEE_UNITS_COMBAT_DESCRIPTION' WHERE ModifierId='LINCOLN_MELEE_BUFF';

-- 16/04/23 +100% toward aqueducs
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'DistrictType', 'DISTRICT_AQUEDUCT'),
	('BBG_LINCOLN_AQUEDUCT_BONUS_PRODUCTION', 'Amount', '100');

-- Base unit discount
-- 14/10/23 removed
-- INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'MODIFIER_PLAYER_ADJUST_UNIT_MAINTENANCE_DISCOUNT');
-- INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
--     ('BBG_LINCOLN_UNITMAINTENANCEDISCOUNT', 'Amount', '1');
-- INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
--     ('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_UNITMAINTENANCEDISCOUNT');

-- 19/06/25 Free units no longer get +5
DELETE FROM UnitAbilityModifiers WHERE ModifierId='LINCOLN_MELEE_BUFF';

-- 14/09/26 Workshops give +2 Culture; Factories and all Power Plants give +3 Science
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
	('BBG_LINCOLN_WORKSHOP_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
	('BBG_LINCOLN_FACTORY_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
	('BBG_LINCOLN_COAL_POWER_PLANT_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
	('BBG_LINCOLN_FOSSIL_FUEL_POWER_PLANT_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE'),
	('BBG_LINCOLN_POWER_PLANT_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');

INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('BBG_LINCOLN_WORKSHOP_CULTURE', 'BuildingType', 'BUILDING_WORKSHOP'),
	('BBG_LINCOLN_WORKSHOP_CULTURE', 'YieldType', 'YIELD_CULTURE'),
	('BBG_LINCOLN_WORKSHOP_CULTURE', 'Amount', '2'),
	('BBG_LINCOLN_FACTORY_SCIENCE', 'BuildingType', 'BUILDING_FACTORY'),
	('BBG_LINCOLN_FACTORY_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('BBG_LINCOLN_FACTORY_SCIENCE', 'Amount', '3'),
	('BBG_LINCOLN_COAL_POWER_PLANT_SCIENCE', 'BuildingType', 'BUILDING_COAL_POWER_PLANT'),
	('BBG_LINCOLN_COAL_POWER_PLANT_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('BBG_LINCOLN_COAL_POWER_PLANT_SCIENCE', 'Amount', '3'),
	('BBG_LINCOLN_FOSSIL_FUEL_POWER_PLANT_SCIENCE', 'BuildingType', 'BUILDING_FOSSIL_FUEL_POWER_PLANT'),
	('BBG_LINCOLN_FOSSIL_FUEL_POWER_PLANT_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('BBG_LINCOLN_FOSSIL_FUEL_POWER_PLANT_SCIENCE', 'Amount', '3'),
	('BBG_LINCOLN_POWER_PLANT_SCIENCE', 'BuildingType', 'BUILDING_POWER_PLANT'),
	('BBG_LINCOLN_POWER_PLANT_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('BBG_LINCOLN_POWER_PLANT_SCIENCE', 'Amount', '3');

INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_WORKSHOP_CULTURE'),
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_FACTORY_SCIENCE'),
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_COAL_POWER_PLANT_SCIENCE'),
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_FOSSIL_FUEL_POWER_PLANT_SCIENCE'),
	('TRAIT_LEADER_LINCOLN', 'BBG_LINCOLN_POWER_PLANT_SCIENCE');
