------------------------------------------------------------------------------
-- Team PVP Balanced mod Secret Societies 3.93
--
-- This is a conflict-safe, self-contained port of the active Secret Society
-- balance from Workshop item 3475173328.  Unrelated Poland, Amani and policy
-- edits that happened to share the upstream SQL file are intentionally out of
-- scope.  Free society titles remain owned by BBG/sql/Secret_Societies.sql so
-- the refund row is inserted exactly once.
------------------------------------------------------------------------------

------------------------------------------------------------------------------
-- Shared discovery and promotion timing
------------------------------------------------------------------------------
UPDATE SecretSocieties
SET DiscoverAtCityStateBaseChance = 100000
WHERE SecretSocietyType IN (
	'SECRETSOCIETY_OWLS_OF_MINERVA',
	'SECRETSOCIETY_HERMETIC_ORDER',
	'SECRETSOCIETY_VOIDSINGERS',
	'SECRETSOCIETY_SANGUINE_PACT'
);

-- ZYL LightweightBalance: investigating any Tribal Village attempts to
-- discover all four societies at the effectively guaranteed base chance.
-- The societies' existing discovery sources remain available as well.
UPDATE SecretSocieties
SET DiscoverAtGoodyHutBaseChance = 100000
WHERE SecretSocietyType IN (
	'SECRETSOCIETY_OWLS_OF_MINERVA',
	'SECRETSOCIETY_HERMETIC_ORDER',
	'SECRETSOCIETY_VOIDSINGERS',
	'SECRETSOCIETY_SANGUINE_PACT'
);

UPDATE GovernorPromotionConditions
SET EarliestGameEra = 'ERA_RENAISSANCE'
WHERE GovernorPromotionType IN (
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_3',
	'GOVERNOR_PROMOTION_HERMETIC_ORDER_3',
	'GOVERNOR_PROMOTION_VOIDSINGERS_3',
	'GOVERNOR_PROMOTION_SANGUINE_PACT_3'
);

------------------------------------------------------------------------------
-- Owls of Minerva
------------------------------------------------------------------------------
UPDATE Buildings
SET Cost = 210,
	PrereqTech = NULL,
	PurchaseYield = NULL
WHERE BuildingType = 'BUILDING_GILDED_VAULT';

INSERT OR IGNORE INTO Building_YieldChanges
	(BuildingType, YieldType, YieldChange)
SELECT 'BUILDING_GILDED_VAULT', 'YIELD_GOLD', 7
WHERE EXISTS (
	SELECT 1 FROM Buildings WHERE BuildingType = 'BUILDING_GILDED_VAULT'
)
UNION ALL
SELECT 'BUILDING_GILDED_VAULT', 'YIELD_CULTURE', 3
WHERE EXISTS (
	SELECT 1 FROM Buildings WHERE BuildingType = 'BUILDING_GILDED_VAULT'
);

UPDATE Building_YieldChanges
SET YieldChange = CASE YieldType
	WHEN 'YIELD_GOLD' THEN 7
	WHEN 'YIELD_CULTURE' THEN 3
END
WHERE BuildingType = 'BUILDING_GILDED_VAULT'
  AND YieldType IN ('YIELD_GOLD', 'YIELD_CULTURE');

UPDATE Building_GreatPersonPoints
SET PointsPerTurn = 3
WHERE BuildingType = 'BUILDING_GILDED_VAULT'
  AND GreatPersonClassType = 'GREAT_PERSON_CLASS_MERCHANT';

DELETE FROM BuildingModifiers
WHERE BuildingType = 'BUILDING_GILDED_VAULT'
  AND ModifierId = 'BUILDING_GILDED_VAULT_CULTURE_MIRRORS_GOLD';

UPDATE ModifierArguments
SET Value = '1'
WHERE ModifierId = 'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_3_SPY_CAPACITY'
  AND Name = 'Amount';

INSERT OR IGNORE INTO GovernorPromotionModifiers
	(GovernorPromotionType, ModifierId)
SELECT 'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_3', ModifierId
FROM GovernorPromotionModifiers
WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4'
  AND ModifierId IN (
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_SCIENCE',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_CULTURE',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_GOLD',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_FAITH'
  );

DELETE FROM GovernorPromotionModifiers
WHERE GovernorPromotionType = 'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4'
  AND ModifierId IN (
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_SCIENCE',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_CULTURE',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_GOLD',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_FAITH'
  );

UPDATE ModifierArguments
SET Value = '150'
WHERE ModifierId IN (
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_SCIENCE',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_CULTURE',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_GOLD',
	'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_SPY_SUCCESS_GRANTS_FAITH'
)
  AND Name = 'Percent';

UPDATE ModifierArguments
SET Value = '5'
WHERE ModifierId = 'GOVERNOR_PROMOTION_OWLS_OF_MINERVA_4_GOLD_INTEREST'
  AND Name = 'Percent';

-- Gilded Shipyard: one Coal per turn after Coal is visible.
INSERT OR IGNORE INTO RequirementSets
	(RequirementSetId, RequirementSetType)
VALUES
	('ZYL_TPVP_PLAYER_CAN_SEE_COAL', 'REQUIREMENTSET_TEST_ALL');

INSERT OR IGNORE INTO RequirementSetRequirements
	(RequirementSetId, RequirementId)
SELECT 'ZYL_TPVP_PLAYER_CAN_SEE_COAL', 'REQUIRES_PLAYER_CAN_SEE_COAL'
WHERE EXISTS (
	SELECT 1 FROM Requirements WHERE RequirementId = 'REQUIRES_PLAYER_CAN_SEE_COAL'
);

INSERT OR IGNORE INTO Modifiers
	(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
	(
		'ZYL_TPVP_GILDED_SHIPYARD_COAL',
		'MODIFIER_PLAYER_ADJUST_FREE_RESOURCE_IMPORT_EXTRACTION',
		'ZYL_TPVP_PLAYER_CAN_SEE_COAL'
	);

INSERT OR REPLACE INTO ModifierArguments
	(ModifierId, Name, Value)
VALUES
	('ZYL_TPVP_GILDED_SHIPYARD_COAL', 'ResourceType', 'RESOURCE_COAL'),
	('ZYL_TPVP_GILDED_SHIPYARD_COAL', 'Amount', 1);

INSERT OR IGNORE INTO BuildingModifiers
	(BuildingType, ModifierId)
SELECT 'BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_COAL'
WHERE EXISTS (
	SELECT 1 FROM Buildings WHERE BuildingType = 'BUILDING_GILDED_Shipyard'
);

-- Mirror the Harbor's base Gold adjacency into Production without allowing
-- policy cards that double adjacency to double the copied Production.  The
-- upstream design tests every threshold from 1 through 12 and grants +1 for
-- each threshold reached.
INSERT OR IGNORE INTO Requirements
	(RequirementId, RequirementType)
VALUES
	('ZYL_TPVP_REQUIRES_HARBOR_DISTRICT', 'REQUIREMENT_DISTRICT_TYPE_MATCHES'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_1', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_2', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_3', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_4', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_5', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_6', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_7', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_8', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_9', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_10', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_11', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_12', 'REQUIREMENT_CITY_HAS_HIGH_ADJACENCY_DISTRICT');

INSERT OR REPLACE INTO RequirementArguments
	(RequirementId, Name, Value)
VALUES
	('ZYL_TPVP_REQUIRES_HARBOR_DISTRICT', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_1', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_1', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_1', 'Amount', 1),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_2', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_2', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_2', 'Amount', 2),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_3', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_3', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_3', 'Amount', 3),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_4', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_4', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_4', 'Amount', 4),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_5', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_5', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_5', 'Amount', 5),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_6', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_6', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_6', 'Amount', 6),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_7', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_7', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_7', 'Amount', 7),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_8', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_8', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_8', 'Amount', 8),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_9', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_9', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_9', 'Amount', 9),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_10', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_10', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_10', 'Amount', 10),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_11', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_11', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_11', 'Amount', 11),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_12', 'DistrictType', 'DISTRICT_HARBOR'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_12', 'YieldType', 'YIELD_GOLD'),
	('ZYL_TPVP_REQUIRES_HARBOR_ADJ_12', 'Amount', 12);

INSERT OR IGNORE INTO RequirementSets
	(RequirementSetId, RequirementSetType)
VALUES
	('ZYL_TPVP_HARBOR_ADJ_1', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_2', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_3', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_4', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_5', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_6', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_7', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_8', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_9', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_10', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_11', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_TPVP_HARBOR_ADJ_12', 'REQUIREMENTSET_TEST_ALL');

INSERT OR IGNORE INTO RequirementSetRequirements
	(RequirementSetId, RequirementId)
VALUES
	('ZYL_TPVP_HARBOR_ADJ_1', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_1', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_1'),
	('ZYL_TPVP_HARBOR_ADJ_2', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_2', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_2'),
	('ZYL_TPVP_HARBOR_ADJ_3', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_3', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_3'),
	('ZYL_TPVP_HARBOR_ADJ_4', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_4', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_4'),
	('ZYL_TPVP_HARBOR_ADJ_5', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_5', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_5'),
	('ZYL_TPVP_HARBOR_ADJ_6', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_6', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_6'),
	('ZYL_TPVP_HARBOR_ADJ_7', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_7', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_7'),
	('ZYL_TPVP_HARBOR_ADJ_8', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_8', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_8'),
	('ZYL_TPVP_HARBOR_ADJ_9', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_9', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_9'),
	('ZYL_TPVP_HARBOR_ADJ_10', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_10', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_10'),
	('ZYL_TPVP_HARBOR_ADJ_11', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_11', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_11'),
	('ZYL_TPVP_HARBOR_ADJ_12', 'ZYL_TPVP_REQUIRES_HARBOR_DISTRICT'),
	('ZYL_TPVP_HARBOR_ADJ_12', 'ZYL_TPVP_REQUIRES_HARBOR_ADJ_12');

INSERT OR IGNORE INTO Modifiers
	(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_1', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_1'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_2', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_2'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_3', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_3'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_4', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_4'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_5', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_5'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_6', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_6'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_7', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_7'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_8', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_8'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_9', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_9'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_10', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_10'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_11', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_11'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_12', 'MODIFIER_PLAYER_DISTRICT_ADJUST_BASE_YIELD_CHANGE', 'ZYL_TPVP_HARBOR_ADJ_12');

INSERT OR REPLACE INTO ModifierArguments
	(ModifierId, Name, Value)
VALUES
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_1', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_1', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_2', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_2', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_3', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_3', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_4', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_4', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_5', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_5', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_6', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_6', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_7', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_7', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_8', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_8', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_9', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_9', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_10', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_10', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_11', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_11', 'Amount', 1),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_12', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_GILDED_SHIPYARD_ADJ_12', 'Amount', 1);

INSERT OR IGNORE INTO BuildingModifiers
	(BuildingType, ModifierId)
VALUES
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_1'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_2'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_3'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_4'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_5'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_6'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_7'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_8'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_9'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_10'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_11'),
	('BUILDING_GILDED_Shipyard', 'ZYL_TPVP_GILDED_SHIPYARD_ADJ_12');

------------------------------------------------------------------------------
-- Hermetic Order and Ley Lines
------------------------------------------------------------------------------
UPDATE Buildings
SET Cost = 180,
	PrereqTech = NULL,
	PurchaseYield = NULL
WHERE BuildingType = 'BUILDING_ALCHEMICAL_SOCIETY';

-- These are also the Ethiopia Pack defaults, but Team PVP explicitly pins
-- them. Keep the values here so a preceding balance component cannot silently
-- change the intended 4 Science / 2 Production profile.
INSERT OR IGNORE INTO Building_YieldChanges
	(BuildingType, YieldType, YieldChange)
SELECT 'BUILDING_ALCHEMICAL_SOCIETY', 'YIELD_SCIENCE', 4
WHERE EXISTS (
	SELECT 1 FROM Buildings WHERE BuildingType = 'BUILDING_ALCHEMICAL_SOCIETY'
)
UNION ALL
SELECT 'BUILDING_ALCHEMICAL_SOCIETY', 'YIELD_PRODUCTION', 2
WHERE EXISTS (
	SELECT 1 FROM Buildings WHERE BuildingType = 'BUILDING_ALCHEMICAL_SOCIETY'
);

UPDATE Building_YieldChanges
SET YieldChange = CASE YieldType
	WHEN 'YIELD_SCIENCE' THEN 4
	WHEN 'YIELD_PRODUCTION' THEN 2
END
WHERE BuildingType = 'BUILDING_ALCHEMICAL_SOCIETY'
  AND YieldType IN ('YIELD_SCIENCE', 'YIELD_PRODUCTION');

INSERT OR REPLACE INTO Resource_YieldChanges
	(ResourceType, YieldType, YieldChange)
SELECT 'RESOURCE_LEY_LINE', 'YIELD_SCIENCE', 1
WHERE EXISTS (
	SELECT 1 FROM Resources WHERE ResourceType = 'RESOURCE_LEY_LINE'
)
UNION ALL
SELECT 'RESOURCE_LEY_LINE', 'YIELD_PRODUCTION', 2
WHERE EXISTS (
	SELECT 1 FROM Resources WHERE ResourceType = 'RESOURCE_LEY_LINE'
);

UPDATE Resources
SET Frequency = 10
WHERE ResourceType = 'RESOURCE_LEY_LINE';

DELETE FROM Resource_ValidTerrains
WHERE ResourceType = 'RESOURCE_LEY_LINE'
  AND TerrainType IN (
	'TERRAIN_TUNDRA',
	'TERRAIN_SNOW',
	'TERRAIN_TUNDRA_HILLS',
	'TERRAIN_SNOW_HILLS',
	'TERRAIN_DESERT_HILLS',
	'TERRAIN_DESERT',
	'TERRAIN_GRASS_HILLS',
	'TERRAIN_PLAINS_HILLS'
  );

UPDATE Adjacency_YieldChanges
SET YieldChange = 1
WHERE ID IN (
	'LeyLine_Culture',
	'LeyLine_Faith',
	'LeyLine_Gold',
	'LeyLine_Production',
	'LeyLine_Science'
);

INSERT OR IGNORE INTO District_Adjacencies
	(DistrictType, YieldChangeId)
SELECT 'DISTRICT_SEOWON', 'LeyLine_Science'
WHERE EXISTS (
	SELECT 1 FROM Districts WHERE DistrictType = 'DISTRICT_SEOWON'
)
  AND EXISTS (
	SELECT 1 FROM Adjacency_YieldChanges WHERE ID = 'LeyLine_Science'
);

UPDATE ModifierArguments
SET Value = 'YIELD_FOOD'
WHERE ModifierId = 'HERMETIC_ORDER_GREAT_ADMIRAL_LEY_LINE_SCIENCE'
  AND Name = 'YieldType';

UPDATE ModifierArguments
SET Value = 'YIELD_PRODUCTION'
WHERE ModifierId = 'HERMETIC_ORDER_GREAT_GENERAL_LEY_LINE_SCIENCE'
  AND Name = 'YieldType';

UPDATE ModifierArguments
SET Value = '2'
WHERE ModifierId = 'HERMETIC_ORDER_GREAT_MERCHANT_LEY_LINE_GOLD'
  AND Name = 'Amount';

-- ZYL LightweightBalance: Ley Lines may be removed for Gold, or improved by
-- a Farm without consuming the Ley Line resource.
INSERT OR REPLACE INTO Resource_Harvests
	(ResourceType, YieldType, Amount, PrereqTech)
SELECT 'RESOURCE_LEY_LINE', 'YIELD_GOLD', 40, NULL
WHERE EXISTS (
	SELECT 1 FROM Resources WHERE ResourceType = 'RESOURCE_LEY_LINE'
);

INSERT OR REPLACE INTO Improvement_ValidResources
	(ImprovementType, ResourceType, MustRemoveFeature)
SELECT 'IMPROVEMENT_FARM', 'RESOURCE_LEY_LINE', 0
WHERE EXISTS (
	SELECT 1 FROM Improvements WHERE ImprovementType = 'IMPROVEMENT_FARM'
)
  AND EXISTS (
	SELECT 1 FROM Resources WHERE ResourceType = 'RESOURCE_LEY_LINE'
);

------------------------------------------------------------------------------
-- Voidsingers
------------------------------------------------------------------------------
UPDATE ModifierArguments
SET Value = CASE ModifierId
	WHEN 'GOVERNOR_PROMOTION_VOIDSINGERS_2_GOLD_FROM_FAITH' THEN '1'
	WHEN 'GOVERNOR_PROMOTION_VOIDSINGERS_2_SCIENCE_FROM_FAITH' THEN '10'
	WHEN 'GOVERNOR_PROMOTION_VOIDSINGERS_2_CULTURE_FROM_FAITH' THEN '4'
END
WHERE Name = 'Amount'
  AND ModifierId IN (
	'GOVERNOR_PROMOTION_VOIDSINGERS_2_GOLD_FROM_FAITH',
	'GOVERNOR_PROMOTION_VOIDSINGERS_2_SCIENCE_FROM_FAITH',
	'GOVERNOR_PROMOTION_VOIDSINGERS_2_CULTURE_FROM_FAITH'
  );

UPDATE Building_YieldChanges
SET YieldChange = 3
WHERE BuildingType = 'BUILDING_OLD_GOD_OBELISK'
  AND YieldType = 'YIELD_FAITH';

UPDATE Units
SET Cost = 60,
	BaseMoves = 6,
	CostProgressionParam1 = 15
WHERE UnitType = 'UNIT_CULTIST';

UPDATE Units_MODE
SET ActionCharges = 1
WHERE UnitType = 'UNIT_CULTIST';

UPDATE ModifierArguments
SET Value = '10'
WHERE ModifierId = 'SPREAD_DISSENT_LOYALTY_DAMAGE'
  AND Name = 'Amount';

-- Relics of the Void are the relic rows requiring the Voidsingers governor.
UPDATE GreatWork_YieldChanges
SET YieldChange = 2
WHERE YieldType = 'YIELD_FAITH'
  AND GreatWorkType IN (
	SELECT GreatWorkType
	FROM GreatWorks_MODE
	WHERE RequiredGovernor = 'GOVERNOR_VOIDSINGERS'
  );

INSERT OR IGNORE INTO Modifiers
	(ModifierId, ModifierType)
VALUES
	('ZYL_TPVP_VOIDSINGER_RELIC_SCIENCE', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD'),
	('ZYL_TPVP_VOIDSINGER_RELIC_CULTURE', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD'),
	('ZYL_TPVP_VOIDSINGER_RELIC_PRODUCTION', 'MODIFIER_PLAYER_CITIES_ADJUST_GREATWORK_YIELD');

INSERT OR REPLACE INTO ModifierArguments
	(ModifierId, Name, Value)
VALUES
	('ZYL_TPVP_VOIDSINGER_RELIC_SCIENCE', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIC'),
	('ZYL_TPVP_VOIDSINGER_RELIC_SCIENCE', 'YieldType', 'YIELD_SCIENCE'),
	('ZYL_TPVP_VOIDSINGER_RELIC_SCIENCE', 'YieldChange', 2),
	('ZYL_TPVP_VOIDSINGER_RELIC_CULTURE', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIC'),
	('ZYL_TPVP_VOIDSINGER_RELIC_CULTURE', 'YieldType', 'YIELD_CULTURE'),
	('ZYL_TPVP_VOIDSINGER_RELIC_CULTURE', 'YieldChange', 2),
	('ZYL_TPVP_VOIDSINGER_RELIC_PRODUCTION', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIC'),
	('ZYL_TPVP_VOIDSINGER_RELIC_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_TPVP_VOIDSINGER_RELIC_PRODUCTION', 'YieldChange', 1);

INSERT OR IGNORE INTO GovernorPromotionModifiers
	(GovernorPromotionType, ModifierId)
VALUES
	('GOVERNOR_PROMOTION_VOIDSINGERS_3', 'ZYL_TPVP_VOIDSINGER_RELIC_SCIENCE'),
	('GOVERNOR_PROMOTION_VOIDSINGERS_3', 'ZYL_TPVP_VOIDSINGER_RELIC_CULTURE'),
	('GOVERNOR_PROMOTION_VOIDSINGERS_3', 'ZYL_TPVP_VOIDSINGER_RELIC_PRODUCTION');

------------------------------------------------------------------------------
-- Sanguine Pact
------------------------------------------------------------------------------
INSERT OR IGNORE INTO ModifierArguments
	(ModifierId, Name, Value)
SELECT 'SANGUINE_PACT_VAMPIRE_COMBAT_STRENGTH_FROM_PROPERTY', 'Max', 3
WHERE EXISTS (
	SELECT 1
	FROM Modifiers
	WHERE ModifierId = 'SANGUINE_PACT_VAMPIRE_COMBAT_STRENGTH_FROM_PROPERTY'
);

UPDATE ModifierArguments
SET Value = '3'
WHERE ModifierId = 'SANGUINE_PACT_VAMPIRE_COMBAT_STRENGTH_FROM_PROPERTY'
  AND Name = 'Max';

UPDATE ModifierArguments
SET Value = '0'
WHERE ModifierId = 'SANGUINE_PACT_VAMPIRE_BARB_COMBAT_STRENGTH_FROM_PROPERTY'
  AND Name = 'Max';

UPDATE ModifierArguments
SET Value = '-2'
WHERE ModifierId = 'SECRET_SOCIETY_INTIMIDATE_ADJACENT_ENEMIES_MODIFIER'
  AND Name = 'Amount';

-- Vampires inherit the melee anti-anti-cavalry bonus.  Team PVP offsets half
-- of it so Vampires have only +5 instead of +10 versus anti-cavalry units.
INSERT OR IGNORE INTO Types
	(Type, Kind)
VALUES
	('ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY', 'KIND_ABILITY');

INSERT OR IGNORE INTO TypeTags
	(Type, Tag)
VALUES
	('ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY', 'CLASS_VAMPIRE');

INSERT OR IGNORE INTO UnitAbilities
	(UnitAbilityType, Name, Description)
VALUES
	(
		'ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY',
		'LOC_ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY_NAME',
		'LOC_ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY_DESCRIPTION'
	);

INSERT OR IGNORE INTO Modifiers
	(ModifierId, ModifierType, SubjectRequirementSetId)
VALUES
	(
		'ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY',
		'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',
		'ANTI_SPEAR_OPPONENT_REQUIREMENTS'
	);

INSERT OR REPLACE INTO ModifierArguments
	(ModifierId, Name, Value)
VALUES
	('ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY', 'Amount', -5);

INSERT OR IGNORE INTO UnitAbilityModifiers
	(UnitAbilityType, ModifierId)
VALUES
	('ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY', 'ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY');

INSERT OR REPLACE INTO ModifierStrings
	(ModifierId, Context, Text)
VALUES
	(
		'ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY',
		'Preview',
		'LOC_ABILITY_ZYL_TPVP_VAMPIRE_ANTI_ANTI_CAVALRY_MODIFIER'
	);

-- Castle caps become 1 at tier 2, +2 at tier 3, +1 at tier 4: 1/3/4 total.
DELETE FROM GovernorPromotionModifiers
WHERE GovernorPromotionType IN (
	'GOVERNOR_PROMOTION_SANGUINE_PACT_2',
	'GOVERNOR_PROMOTION_SANGUINE_PACT_3'
)
  AND ModifierId IN (
	'SECRET_SOCIETY_GRANT_ONE_VAMPIRE_BUILD',
	'SECRET_SOCIETY_GRANT_TWO_VAMPIRE_BUILDS'
  );

INSERT OR IGNORE INTO GovernorPromotionModifiers
	(GovernorPromotionType, ModifierId)
VALUES
	('GOVERNOR_PROMOTION_SANGUINE_PACT_2', 'SECRET_SOCIETY_GRANT_ONE_VAMPIRE_BUILD'),
	('GOVERNOR_PROMOTION_SANGUINE_PACT_3', 'SECRET_SOCIETY_GRANT_TWO_VAMPIRE_BUILDS');

UPDATE Improvements
SET CanBuildOutsideTerritory = 0
WHERE ImprovementType = 'IMPROVEMENT_VAMPIRE_CASTLE';

DELETE FROM UnitRetreats_XP1
WHERE UnitRetreatType = 'UNIT_RETREAT_VAMPIRE_TO_CASTLE'
  AND UnitType = 'UNIT_VAMPIRE'
  AND ImprovementType = 'IMPROVEMENT_VAMPIRE_CASTLE';

-- Remove the base game's globally attached dynamic copy-yields effect.  The
-- fixed castle yields and explicit adjacencies below avoid the multiplayer
-- perspective/reload desynchronization in that effect.
DELETE FROM GameModifiers
WHERE ModifierId = 'SECRET_SOCIETIES_ATTACH_PLAYER_CASTLES_GAIN_ADJACENT_YIELDS';

INSERT OR REPLACE INTO Improvement_YieldChanges
	(ImprovementType, YieldType, YieldChange)
VALUES
	('IMPROVEMENT_VAMPIRE_CASTLE', 'YIELD_FOOD', 9),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'YIELD_PRODUCTION', 5),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'YIELD_FAITH', 0),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'YIELD_GOLD', 0),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'YIELD_CULTURE', 0),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'YIELD_SCIENCE', 0);

INSERT OR IGNORE INTO Adjacency_YieldChanges
	(ID, Description, YieldType, YieldChange, TilesRequired, AdjacentTerrain)
VALUES
	('ZYL_TPVP_VC_TUNDRA_HILLS', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'TERRAIN_TUNDRA_HILLS'),
	('ZYL_TPVP_VC_PLAINS_HILLS', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'TERRAIN_PLAINS_HILLS'),
	('ZYL_TPVP_VC_GRASS_HILLS', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'TERRAIN_GRASS_HILLS'),
	('ZYL_TPVP_VC_DESERT_HILLS', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'TERRAIN_DESERT_HILLS');

INSERT OR IGNORE INTO Adjacency_YieldChanges
	(ID, Description, YieldType, YieldChange, TilesRequired, AdjacentFeature)
VALUES
	('ZYL_TPVP_VC_FOREST', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'FEATURE_FOREST'),
	('ZYL_TPVP_VC_JUNGLE', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'FEATURE_JUNGLE');

INSERT OR IGNORE INTO Adjacency_YieldChanges
	(ID, Description, YieldType, YieldChange, TilesRequired, AdjacentResourceClass)
VALUES
	('ZYL_TPVP_VC_BONUS_RESOURCE', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'RESOURCECLASS_BONUS'),
	('ZYL_TPVP_VC_LUXURY_RESOURCE', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'RESOURCECLASS_LUXURY'),
	('ZYL_TPVP_VC_STRATEGIC_RESOURCE', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'RESOURCECLASS_STRATEGIC');

INSERT OR IGNORE INTO Adjacency_YieldChanges
	(ID, Description, YieldType, YieldChange, TilesRequired, AdjacentImprovement)
VALUES
	('ZYL_TPVP_VC_MINE', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_MINE'),
	('ZYL_TPVP_VC_LUMBER_MILL', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_LUMBER_MILL'),
	('ZYL_TPVP_VC_FISHING_BOATS', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_FISHING_BOATS'),
	('ZYL_TPVP_VC_PASTURE', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_PASTURE'),
	('ZYL_TPVP_VC_PLANTATION', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_PLANTATION'),
	('ZYL_TPVP_VC_QUARRY', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_QUARRY'),
	('ZYL_TPVP_VC_CAMP', 'Placeholder', 'YIELD_PRODUCTION', 1, 1, 'IMPROVEMENT_CAMP');

-- Only create district rows for districts that exist in the current DLC set.
INSERT OR IGNORE INTO Adjacency_YieldChanges
	(ID, Description, YieldType, YieldChange, TilesRequired, AdjacentDistrict)
SELECT
	'ZYL_TPVP_VC_DISTRICT_' || DistrictType,
	'Placeholder',
	CASE
		WHEN DistrictType IN ('DISTRICT_HOLY_SITE', 'DISTRICT_LAVRA') THEN 'YIELD_FAITH'
		WHEN DistrictType IN (
			'DISTRICT_HARBOR',
			'DISTRICT_ROYAL_NAVY_DOCKYARD',
			'DISTRICT_COTHON',
			'DISTRICT_COMMERCIAL_HUB',
			'DISTRICT_SUGUBA'
		) THEN 'YIELD_GOLD'
		WHEN DistrictType IN ('DISTRICT_THEATER', 'DISTRICT_ACROPOLIS') THEN 'YIELD_CULTURE'
		WHEN DistrictType IN (
			'DISTRICT_INDUSTRIAL_ZONE',
			'DISTRICT_HANSA',
			'DISTRICT_OPPIDUM'
		) THEN 'YIELD_PRODUCTION'
		ELSE 'YIELD_SCIENCE'
	END,
	CASE
		WHEN DistrictType IN (
			'DISTRICT_HARBOR',
			'DISTRICT_ROYAL_NAVY_DOCKYARD',
			'DISTRICT_COTHON',
			'DISTRICT_COMMERCIAL_HUB',
			'DISTRICT_SUGUBA'
		) THEN 2
		ELSE 1
	END,
	1,
	DistrictType
FROM Districts
WHERE DistrictType IN (
	'DISTRICT_HOLY_SITE',
	'DISTRICT_LAVRA',
	'DISTRICT_HARBOR',
	'DISTRICT_ROYAL_NAVY_DOCKYARD',
	'DISTRICT_COTHON',
	'DISTRICT_COMMERCIAL_HUB',
	'DISTRICT_SUGUBA',
	'DISTRICT_THEATER',
	'DISTRICT_ACROPOLIS',
	'DISTRICT_INDUSTRIAL_ZONE',
	'DISTRICT_HANSA',
	'DISTRICT_OPPIDUM',
	'DISTRICT_CAMPUS',
	'DISTRICT_OBSERVATORY',
	'DISTRICT_SEOWON'
);

INSERT OR IGNORE INTO Improvement_Adjacencies
	(ImprovementType, YieldChangeId)
VALUES
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_TUNDRA_HILLS'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_PLAINS_HILLS'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_GRASS_HILLS'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_DESERT_HILLS'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_FOREST'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_JUNGLE'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_BONUS_RESOURCE'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_LUXURY_RESOURCE'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_STRATEGIC_RESOURCE'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_MINE'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_LUMBER_MILL'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_FISHING_BOATS'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_PASTURE'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_PLANTATION'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_QUARRY'),
	('IMPROVEMENT_VAMPIRE_CASTLE', 'ZYL_TPVP_VC_CAMP');

INSERT OR IGNORE INTO Improvement_Adjacencies
	(ImprovementType, YieldChangeId)
SELECT 'IMPROVEMENT_VAMPIRE_CASTLE', ID
FROM Adjacency_YieldChanges
WHERE ID LIKE 'ZYL_TPVP_VC_DISTRICT_%';
