--==================
-- Canada
--==================
-- INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId)
--  VALUES
--  ('TRAIT_LEADER_LAST_BEST_WEST', 'TUNDRA_EXTRA_FOOD_CPLMOD'           ),
--  ('TRAIT_LEADER_LAST_BEST_WEST', 'TUNDRA_HILLS_EXTRA_FOOD_CPLMOD'     ),
--  ('TRAIT_LEADER_LAST_BEST_WEST', 'NATIONAL_PARK_FOOD_YIELDS_CPLMOD'   ),
--  ('TRAIT_LEADER_LAST_BEST_WEST', 'NATIONAL_PARK_PROD_YIELDS_CPLMOD'   );
-- INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId, OwnerRequirementSetId)
--  VALUES
--  ('TUNDRA_EXTRA_FOOD_CPLMOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_TUNDRA_REQUIREMENTS', NULL),
--  ('TUNDRA_HILLS_EXTRA_FOOD_CPLMOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_TUNDRA_HILLS_REQUIREMENTS', NULL),
--  ('NATIONAL_PARK_FOOD_YIELDS_CPLMOD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', 'CITY_HAS_NATIONAL_PARK_REQUREMENTS', NULL),
--  ('NATIONAL_PARK_PROD_YIELDS_CPLMOD', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_CHANGE', 'CITY_HAS_NATIONAL_PARK_REQUREMENTS', NULL);
-- INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value)
--  VALUES
--  ('TUNDRA_EXTRA_FOOD_CPLMOD', 'YieldType', 'YIELD_FOOD'      ),
--  ('TUNDRA_EXTRA_FOOD_CPLMOD', 'Amount', '1'               ),
--  ('TUNDRA_HILLS_EXTRA_FOOD_CPLMOD', 'YieldType', 'YIELD_FOOD'      ),
--  ('TUNDRA_HILLS_EXTRA_FOOD_CPLMOD', 'Amount', '1'               ),
--  ('NATIONAL_PARK_FOOD_YIELDS_CPLMOD', 'YieldType', 'YIELD_FOOD'      ),
--  ('NATIONAL_PARK_FOOD_YIELDS_CPLMOD', 'Amount', '4'               ),
--  ('NATIONAL_PARK_PROD_YIELDS_CPLMOD', 'YieldType', 'YIELD_PRODUCTION'),
--  ('NATIONAL_PARK_PROD_YIELDS_CPLMOD', 'Amount', '4'               );
-- 15/05/2021 : Canada +1 food per city center
INSERT INTO Modifiers(ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_TOUNDRA_CITY_EXTRA_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_IS_TUNDRA_CITY_REQUIREMENTS'),
    ('BBG_TOUNDRA_HILLS_CITY_EXTRA_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_IS_TUNDRA_HILL_CITY_REQUIREMENTS');
INSERT INTO ModifierArguments(ModifierId, Name, Value) VALUES
    ('BBG_TOUNDRA_CITY_EXTRA_FOOD', 'YieldType', 'YIELD_FOOD'),
    ('BBG_TOUNDRA_CITY_EXTRA_FOOD', 'Amount', '1'),
    ('BBG_TOUNDRA_HILLS_CITY_EXTRA_FOOD', 'YieldType', 'YIELD_FOOD'),
    ('BBG_TOUNDRA_HILLS_CITY_EXTRA_FOOD', 'Amount', '1');
INSERT INTO RequirementSets(RequirementSetId, RequirementSetType) VALUES
    ('PLOT_IS_TUNDRA_CITY_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
    ('PLOT_IS_TUNDRA_HILL_CITY_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements(RequirementSetId, RequirementId) VALUES
    ('PLOT_IS_TUNDRA_CITY_REQUIREMENTS', 'REQUIRES_PLOT_HAS_TUNDRA'),
    ('PLOT_IS_TUNDRA_CITY_REQUIREMENTS', 'BBG_REQUIRES_PLOT_IS_CITY_CENTER'),
    ('PLOT_IS_TUNDRA_HILL_CITY_REQUIREMENTS', 'REQUIRES_PLOT_HAS_TUNDRA_HILLS'),
    ('PLOT_IS_TUNDRA_HILL_CITY_REQUIREMENTS', 'BBG_REQUIRES_PLOT_IS_CITY_CENTER');
INSERT INTO Requirements(RequirementId, RequirementType) VALUES
    ('BBG_REQUIRES_PLOT_IS_CITY_CENTER', 'REQUIREMENT_PLOT_DISTRICT_TYPE_MATCHES');
INSERT INTO RequirementArguments(RequirementId, Name, Value) VALUES
    ('BBG_REQUIRES_PLOT_IS_CITY_CENTER', 'DistrictType', 'DISTRICT_CITY_CENTER');
INSERT INTO TraitModifiers(TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_LAST_BEST_WEST', 'BBG_TOUNDRA_CITY_EXTRA_FOOD'),
    ('TRAIT_LEADER_LAST_BEST_WEST', 'BBG_TOUNDRA_HILLS_CITY_EXTRA_FOOD');

-- Hockey rink at Civil Service
UPDATE Improvements SET PrereqCivic='CIVIC_DIPLOMATIC_SERVICE' WHERE ImprovementType='IMPROVEMENT_ICE_HOCKEY_RINK';
-- Move the existing +2 Food and +2 Production bonus from Professional Sports to Conservation.
UPDATE Improvement_BonusYieldChanges
SET PrereqCivic='CIVIC_CONSERVATION'
WHERE ImprovementType='IMPROVEMENT_ICE_HOCKEY_RINK'
  AND YieldType IN ('YIELD_FOOD', 'YIELD_PRODUCTION')
  AND PrereqCivic='CIVIC_PROFESSIONAL_SPORTS';
-- Mounties get a base combat buff and combat buff from nearby parks radius increased
UPDATE Units SET Combat=70, Cost=360 WHERE UnitType='UNIT_CANADA_MOUNTIE';
UPDATE RequirementArguments SET Value='4' WHERE RequirementId='UNIT_PARK_REQUIREMENT'       AND Name='MaxDistance';
UPDATE RequirementArguments SET Value='4' WHERE RequirementId='UNIT_OWNER_PARK_REQUIREMENT' AND Name='MaxDistance';

-- Mounties replace Cavalry, so Canada's existing Courser-to-Cavalry upgrade is redirected
-- to the Mountie by the unique-unit replacement system. Mounties then upgrade to Helicopters.
INSERT OR REPLACE INTO UnitReplaces (CivUniqueUnitType, ReplacesUnitType) VALUES
    ('UNIT_CANADA_MOUNTIE', 'UNIT_CAVALRY');
INSERT OR REPLACE INTO UnitUpgrades (Unit, UpgradeUnit) VALUES
    ('UNIT_CANADA_MOUNTIE', 'UNIT_HELICOPTER');
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType) VALUES
    ('ZYL_CANADA_MOUNTIE_FAITH_PURCHASE', 'MODIFIER_PLAYER_CITIES_ENABLE_UNIT_FAITH_PURCHASE');
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('ZYL_CANADA_MOUNTIE_FAITH_PURCHASE', 'Tag', 'CLASS_MOUNTIE');
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_CIVILIZATION_UNIT_CANADA_MOUNTIE', 'ZYL_CANADA_MOUNTIE_FAITH_PURCHASE');

-- Four tiles belonging to a National Park each receive +2 Food and +2 Production.
-- The matching plot property is maintained by canada_national_park_yields.lua.
INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES
    ('ZYL_CANADA_REQUIRES_NATIONAL_PARK_PLOT', 'REQUIREMENT_PLOT_PROPERTY_MATCHES');
INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) VALUES
    ('ZYL_CANADA_REQUIRES_NATIONAL_PARK_PLOT', 'PropertyName', 'ZYL_CANADA_NATIONAL_PARK'),
    ('ZYL_CANADA_REQUIRES_NATIONAL_PARK_PLOT', 'PropertyMinimum', '1');
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('ZYL_CANADA_NATIONAL_PARK_PLOT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');
INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('ZYL_CANADA_NATIONAL_PARK_PLOT_REQUIREMENTS', 'ZYL_CANADA_REQUIRES_NATIONAL_PARK_PLOT');
INSERT OR IGNORE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('ZYL_CANADA_NATIONAL_PARK_FOOD', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'ZYL_CANADA_NATIONAL_PARK_PLOT_REQUIREMENTS'),
    ('ZYL_CANADA_NATIONAL_PARK_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'ZYL_CANADA_NATIONAL_PARK_PLOT_REQUIREMENTS');
INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('ZYL_CANADA_NATIONAL_PARK_FOOD', 'YieldType', 'YIELD_FOOD'),
    ('ZYL_CANADA_NATIONAL_PARK_FOOD', 'Amount', '2'),
    ('ZYL_CANADA_NATIONAL_PARK_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION'),
    ('ZYL_CANADA_NATIONAL_PARK_PRODUCTION', 'Amount', '2');
INSERT OR IGNORE INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_CIVILIZATION_FACES_OF_PEACE', 'ZYL_CANADA_NATIONAL_PARK_FOOD'),
    ('TRAIT_CIVILIZATION_FACES_OF_PEACE', 'ZYL_CANADA_NATIONAL_PARK_PRODUCTION');


-- 18/12/25 Canada : Pastures in Tundra receive +1 Food.
INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
    ('BBG_PLOT_HAS_TUNDRA_HILLS_PASTURE_REQSET', 'REQUIREMENTSET_TEST_ALL'),
    ('BBG_PLOT_HAS_TUNDRA_PASTURE_REQSET', 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
    ('BBG_PLOT_HAS_TUNDRA_HILLS_PASTURE_REQSET', 'REQUIRES_PLOT_HAS_TUNDRA_HILLS'),
    ('BBG_PLOT_HAS_TUNDRA_HILLS_PASTURE_REQSET', 'REQUIRES_PLOT_HAS_PASTURE'),
    ('BBG_PLOT_HAS_TUNDRA_PASTURE_REQSET', 'REQUIRES_PLOT_HAS_TUNDRA'),
    ('BBG_PLOT_HAS_TUNDRA_PASTURE_REQSET', 'REQUIRES_PLOT_HAS_PASTURE');

INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
    ('BBG_TUNDRA_HILLS_PASTURES_FOOD_CANADA', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_PLOT_HAS_TUNDRA_HILLS_PASTURE_REQSET'),
    ('BBG_TUNDRA_PASTURES_FOOD_CANADA', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'BBG_PLOT_HAS_TUNDRA_PASTURE_REQSET');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
    ('BBG_TUNDRA_HILLS_PASTURES_FOOD_CANADA', 'YieldType', 'YIELD_FOOD'),
    ('BBG_TUNDRA_HILLS_PASTURES_FOOD_CANADA', 'Amount', 1),
    ('BBG_TUNDRA_PASTURES_FOOD_CANADA', 'YieldType', 'YIELD_FOOD'),
    ('BBG_TUNDRA_PASTURES_FOOD_CANADA', 'Amount', 1);
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES
    ('TRAIT_LEADER_LAST_BEST_WEST', 'BBG_TUNDRA_HILLS_PASTURES_FOOD_CANADA'),
    ('TRAIT_LEADER_LAST_BEST_WEST', 'BBG_TUNDRA_PASTURES_FOOD_CANADA');

