-- ============================================================================
-- ZYL 伟人改动（基础游戏 + R&F/GS 伟人部分）
-- 加载顺序：260000030（在 BBG GreatPeoples 11611/11648 之后、ZYL 文本之前）
-- 配套文本：lang/ZYL_GreatPeople_Text.xml（LOC_ZYL_GREATPERSON_*_ACTIVE）
-- ============================================================================

-- ========== 1. 阿耶波多：5 个随机古典/中世纪科技尤里卡（原 3） ==========
UPDATE ModifierArguments SET Value='5'
WHERE ModifierId='GREATPERSON_3CLASSICALMEDIEVALTECHBOOSTS' AND Name='Amount';

-- ========== 2. 欧几里得：立刻完成"数学" + 获得 2 名使者 ==========
-- 删除旧的"数学尤里卡 + 1 个中世纪科技尤里卡"
DELETE FROM GreatPersonIndividualActionModifiers
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_EUCLID'
  AND ModifierId IN ('GREATPERSON_MATHTECHBOOST','GREATPERSON_1MEDIEVALTECHBOOST');

-- 新建：立刻完成数学科技
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('ZYL_GREATPERSON_GRANT_TECH_MATHEMATICS','MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('ZYL_GREATPERSON_GRANT_TECH_MATHEMATICS','TechType','TECH_MATHEMATICS');

-- 新建：获得 2 名使者（专属 modifier，避免影响 Raja Todar Mal 的 1 使者）
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('ZYL_GREATPERSON_2_INFLUENCE_TOKENS','MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('ZYL_GREATPERSON_2_INFLUENCE_TOKENS','Amount','2');

INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType) VALUES
 ('GREAT_PERSON_INDIVIDUAL_EUCLID','ZYL_GREATPERSON_GRANT_TECH_MATHEMATICS','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE'),
 ('GREAT_PERSON_INDIVIDUAL_EUCLID','ZYL_GREATPERSON_2_INFLUENCE_TOKENS','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

-- ========== 3. 柯莱欧司：使用次数 1 → 2 ==========
UPDATE GreatPersonIndividuals SET ActionCharges=2
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_COLAEUS';

-- ========== 4. 克拉苏：使用次数 3 → 5 ==========
UPDATE GreatPersonIndividuals SET ActionCharges=5
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARCUS_LICINIUS_CRASSUS';

-- ========== 5. 艾布·卡西姆：新增"图书馆 +1 食物" ==========
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('ZYL_GREATPERSON_LIBRARIES_FOOD','MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
 ('ZYL_GREATPERSON_LIBRARIES_FOOD','BuildingType','BUILDING_LIBRARY'),
 ('ZYL_GREATPERSON_LIBRARIES_FOOD','YieldType','YIELD_FOOD'),
 ('ZYL_GREATPERSON_LIBRARIES_FOOD','Amount','1');
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType)
VALUES ('GREAT_PERSON_INDIVIDUAL_ABU_AL_QASIM_AL_ZAHRAWI','ZYL_GREATPERSON_LIBRARIES_FOOD','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

-- ========== 6. 奥马尔·海亚姆：3 个科技尤里卡 + 2 个市政鼓舞（原 2+1） ==========
UPDATE ModifierArguments SET Value='3'
WHERE ModifierId='GREATPERSON_2MEDIEVALRENAISSANCETECHBOOSTS' AND Name='Amount';
UPDATE ModifierArguments SET Value='2'
WHERE ModifierId='GREATPERSON_1MEDIEVALRENAISSANCECIVICBOOST' AND Name='Amount';

-- ========== 7. 皮耶罗·迪·巴尔迪：使者 1 → 2（换用专属 modifier，避免影响 Todar Mal） ==========
DELETE FROM GreatPersonIndividualActionModifiers
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_PIERO_DE_BARDI'
  AND ModifierId='GREATPERSON_INFLUENCE_TOKENS_SMALL';
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType)
VALUES ('GREAT_PERSON_INDIVIDUAL_PIERO_DE_BARDI','ZYL_GREATPERSON_2_INFLUENCE_TOKENS','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');
-- ========== 8. 圣乔治·詹姆斯：新增"远古城墙 +1 文化"，使用次数 3 → 2 ==========
UPDATE GreatPersonIndividuals SET ActionCharges=2
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JAMES_OF_ST_GEORGE';
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('ZYL_GREATPERSON_WALLS_CULTURE','MODIFIER_PLAYER_CITIES_ADJUST_BUILDING_YIELD_CHANGE');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
 ('ZYL_GREATPERSON_WALLS_CULTURE','BuildingType','BUILDING_WALLS'),
 ('ZYL_GREATPERSON_WALLS_CULTURE','YieldType','YIELD_CULTURE'),
 ('ZYL_GREATPERSON_WALLS_CULTURE','Amount','1');
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType)
VALUES ('GREAT_PERSON_INDIVIDUAL_JAMES_OF_ST_GEORGE','ZYL_GREATPERSON_WALLS_CULTURE','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

-- ========== 9. 伽利略：每山脉格 250 → 300 科技值 ==========
UPDATE ModifierArguments SET Value='300'
WHERE Name='Amount' AND ModifierId IN (
 'GREATPERSON_ADJACENT_GRASSMOUNTAIN_SCIENCE',
 'GREATPERSON_ADJACENT_PLAINSMOUNTAIN_SCIENCE',
 'GREATPERSON_ADJACENT_DESERTMOUNTAIN_SCIENCE',
 'GREATPERSON_ADJACENT_TUNDRAMOUNTAIN_SCIENCE',
 'GREATPERSON_ADJACENT_SNOWMOUNTAIN_SCIENCE');

-- ========== 10. 埃米莉·夏特莱：5 个文艺复兴/工业科技尤里卡（原 3） ==========
UPDATE ModifierArguments SET Value='5'
WHERE ModifierId='GREATPERSON_3RENAISSANCEINDUSTRIALTECHBOOSTS' AND Name='Amount';

-- ========== 11. 张骞：删除外国商路双方 +2 金币，只保留贸易路线容量 ==========
DELETE FROM GreatPersonIndividualActionModifiers
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ZHANG_QIAN'
  AND ModifierId IN ('GREATPERSON_GOLD_TO_INCOMING_FOREIGN_ROUTES','GREATPERSON_GOLD_FROM_INCOMING_FOREIGN_ROUTES');

-- ========== 12. 马可波罗：删除外国商路双方 +2 金币，保留贸易路线容量 + 免费商人 ==========
DELETE FROM GreatPersonIndividualActionModifiers
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARCO_POLO'
  AND ModifierId IN ('GREATPERSON_GOLD_TO_INCOMING_FOREIGN_ROUTES','GREATPERSON_GOLD_FROM_INCOMING_FOREIGN_ROUTES');

-- ========== 13. 毕昇：印刷术尤里卡 → 直接完成印刷术 ==========
DELETE FROM GreatPersonIndividualActionModifiers
WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_BI_SHENG'
  AND ModifierId='GREATPERSON_PRINTINGTECHBOOST';
INSERT INTO Modifiers (ModifierId, ModifierType)
VALUES ('ZYL_GREATPERSON_GRANT_TECH_PRINTING','MODIFIER_PLAYER_GRANT_SPECIFIC_TECHNOLOGY');
INSERT INTO ModifierArguments (ModifierId, Name, Value)
VALUES ('ZYL_GREATPERSON_GRANT_TECH_PRINTING','TechType','TECH_PRINTING');
INSERT INTO GreatPersonIndividualActionModifiers (GreatPersonIndividualType, ModifierId, AttachmentTargetType)
VALUES ('GREAT_PERSON_INDIVIDUAL_BI_SHENG','ZYL_GREATPERSON_GRANT_TECH_PRINTING','GREAT_PERSON_ACTION_ATTACHMENT_TARGET_DISTRICT_IN_TILE');

-- ============================================================================
-- 全部 69 位伟人：能力文本覆盖为 LOC_ZYL_GREATPERSON_*_ACTIVE
-- （正文 = 最终能力 + 使用次数标注，中英双语见 lang/ZYL_GreatPeople_Text.xml）
-- ============================================================================
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ABDUS_SALAM_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ABDUS_SALAM';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ABU_AL_QASIM_AL_ZAHRAWI_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ABU_AL_QASIM_AL_ZAHRAWI';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ADA_LOVELACE_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ADA_LOVELACE';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ADAM_SMITH_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ADAM_SMITH';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ALAN_TURING_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ALAN_TURING';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ALBERT_EINSTEIN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ALBERT_EINSTEIN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ALFRED_NOBEL_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ALFRED_NOBEL';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ALVAR_AALTO_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ALVAR_AALTO';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ARYABHATA_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ARYABHATA';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_BI_SHENG_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_BI_SHENG';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_CARL_SAGAN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_CARL_SAGAN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_CHARLES_CORREA_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_CHARLES_CORREA';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_CHARLES_DARWIN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_CHARLES_DARWIN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_COLAEUS_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_COLAEUS';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_DMITRI_MENDELEEV_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_DMITRI_MENDELEEV';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_EMILIE_DU_CHATELET_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_EMILIE_DU_CHATELET';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ERWIN_SCHRODINGER_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ERWIN_SCHRODINGER';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ESTEE_LAUDER_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ESTEE_LAUDER';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_EUCLID_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_EUCLID';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_FILIPPO_BRUNELLESCHI_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_FILIPPO_BRUNELLESCHI';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_GALILEO_GALILEI_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_GALILEO_GALILEI';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_GIOVANNI_DE_MEDICI_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_GIOVANNI_DE_MEDICI';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_GUSTAVE_EIFFEL_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_GUSTAVE_EIFFEL';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_HELENA_RUBINSTEIN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_HELENA_RUBINSTEIN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_HILDEGARD_OF_BINGEN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_HILDEGARD_OF_BINGEN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_HYPATIA_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_HYPATIA';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_IBN_FADLAN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_IBN_FADLAN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_IBN_KHALDUN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_IBN_KHALDUN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_IMHOTEP_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_IMHOTEP';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_IRENE_OF_ATHENS_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_IRENE_OF_ATHENS';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ISAAC_NEWTON_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ISAAC_NEWTON';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ISIDORE_OF_MILETUS_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ISIDORE_OF_MILETUS';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JAKOB_FUGGER_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JAKOB_FUGGER';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JAMES_OF_ST_GEORGE_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JAMES_OF_ST_GEORGE';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JAMES_WATT_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JAMES_WATT';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JAMES_YOUNG_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JAMES_YOUNG';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JAMSETJI_TATA_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JAMSETJI_TATA';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JANAKI_AMMAL_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JANAKI_AMMAL';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JANE_DREW_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JANE_DREW';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JOHN_A_ROEBLING_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JOHN_A_ROEBLING';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JOHN_JACOB_ASTOR_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JOHN_JACOB_ASTOR';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JOHN_ROCKEFELLER_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JOHN_ROCKEFELLER';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JOHN_SPILSBURY_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JOHN_SPILSBURY';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_JOSEPH_PAXTON_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_JOSEPH_PAXTON';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_KENZO_TANGE_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_KENZO_TANGE';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_LEONARDO_DA_VINCI_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_LEONARDO_DA_VINCI';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_LEVI_STRAUSS_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_LEVI_STRAUSS';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MARCO_POLO_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARCO_POLO';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MARCUS_LICINIUS_CRASSUS_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARCUS_LICINIUS_CRASSUS';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MARGARET_MEAD_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARGARET_MEAD';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MARY_KATHERINE_GODDARD_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARY_KATHERINE_GODDARD';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MARY_LEAKEY_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MARY_LEAKEY';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MASARU_IBUKA_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MASARU_IBUKA';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MELITTA_BENTZ_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MELITTA_BENTZ';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_MIMAR_SINAN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_MIMAR_SINAN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_NIKOLA_TESLA_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_NIKOLA_TESLA';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_OMAR_KHAYYAM_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_OMAR_KHAYYAM';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_PIERO_DE_BARDI_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_PIERO_DE_BARDI';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_RAJA_TODAR_MAL_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_RAJA_TODAR_MAL';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ROBERT_GODDARD_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ROBERT_GODDARD';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_SARAH_BREEDLOVE_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_SARAH_BREEDLOVE';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_SERGEI_KOROLEV_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_SERGEI_KOROLEV';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_SHAH_JAHAN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_SHAH_JAHAN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_STAMFORD_RAFFLES_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_STAMFORD_RAFFLES';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_STEPHANIE_KWOLEK_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_STEPHANIE_KWOLEK';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_WERNHER_VON_BRAUN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_WERNHER_VON_BRAUN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ZHANG_HENG_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ZHANG_HENG';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ZHANG_QIAN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ZHANG_QIAN';
UPDATE GreatPersonIndividuals SET ActionEffectTextOverride='LOC_ZYL_GREATPERSON_ZHOU_DAGUAN_ACTIVE' WHERE GreatPersonIndividualType='GREAT_PERSON_INDIVIDUAL_ZHOU_DAGUAN';
