------------------------------------------------------------------------------
-- Selected ZYL Lightweight Balance pantheons for ZYLPVPMOD.
--
-- This contains the thirteen Lightweight Balance pantheons selected for the
-- integrated ruleset plus ZYL's Druid pantheon. Keep the ZYL_LBM IDs so saves
-- and UI icon lookups stay compatible with their upstream definitions.
------------------------------------------------------------------------------

-- Wealth Goddess needs a ruleset-independent district-prerequisite modifier.
INSERT OR IGNORE INTO Types (Type, Kind) VALUES
	('MODIFIER_ZYL_LBM_PLAYER_ADJUST_DISTRICT_UNLOCK', 'KIND_MODIFIER');

INSERT OR IGNORE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
	('MODIFIER_ZYL_LBM_PLAYER_ADJUST_DISTRICT_UNLOCK', 'COLLECTION_OWNER', 'EFFECT_ADJUST_DISTRICT_PREREQ');

INSERT OR IGNORE INTO Types (Type, Kind) VALUES
	('BELIEF_ZYL_LBM_MOON_GODDESS', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_COMMERCE_GODDESS', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_SUN_GOD', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_ORAL_TRADITION', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_EARTH_SPIRITS', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_GARDEN_GODDESS', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_WEALTH_GODDESS', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_TRADE_GOD', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_PATH_OF_CONQUEST', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_SACRED_INSCRIPTIONS', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_GRANARY_GOD', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_REEF_PARADISE', 'KIND_BELIEF'),
	('BELIEF_ZYL_LBM_SIREN', 'KIND_BELIEF'),
	('BELIEF_ZYL_DRUID', 'KIND_BELIEF');

INSERT OR IGNORE INTO Beliefs (BeliefType, Name, Description, BeliefClassType) VALUES
	('BELIEF_ZYL_LBM_MOON_GODDESS', 'LOC_BELIEF_ZYL_LBM_MOON_GODDESS_NAME', 'LOC_BELIEF_ZYL_LBM_MOON_GODDESS_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_COMMERCE_GODDESS', 'LOC_BELIEF_ZYL_LBM_COMMERCE_GODDESS_NAME', 'LOC_BELIEF_ZYL_LBM_COMMERCE_GODDESS_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_SUN_GOD', 'LOC_BELIEF_ZYL_LBM_SUN_GOD_NAME', 'LOC_BELIEF_ZYL_LBM_SUN_GOD_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_ORAL_TRADITION', 'LOC_BELIEF_ZYL_LBM_ORAL_TRADITION_NAME', 'LOC_BELIEF_ZYL_LBM_ORAL_TRADITION_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_EARTH_SPIRITS', 'LOC_BELIEF_ZYL_LBM_EARTH_SPIRITS_NAME', 'LOC_BELIEF_ZYL_LBM_EARTH_SPIRITS_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_GARDEN_GODDESS', 'LOC_BELIEF_ZYL_LBM_GARDEN_GODDESS_NAME', 'LOC_BELIEF_ZYL_LBM_GARDEN_GODDESS_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_WEALTH_GODDESS', 'LOC_BELIEF_ZYL_LBM_WEALTH_GODDESS_NAME', 'LOC_BELIEF_ZYL_LBM_WEALTH_GODDESS_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_TRADE_GOD', 'LOC_BELIEF_ZYL_LBM_TRADE_GOD_NAME', 'LOC_BELIEF_ZYL_LBM_TRADE_GOD_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_PATH_OF_CONQUEST', 'LOC_BELIEF_ZYL_LBM_PATH_OF_CONQUEST_NAME', 'LOC_BELIEF_ZYL_LBM_PATH_OF_CONQUEST_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_SACRED_INSCRIPTIONS', 'LOC_BELIEF_ZYL_LBM_SACRED_INSCRIPTIONS_NAME', 'LOC_BELIEF_ZYL_LBM_SACRED_INSCRIPTIONS_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_GRANARY_GOD', 'LOC_BELIEF_ZYL_LBM_GRANARY_GOD_NAME', 'LOC_BELIEF_ZYL_LBM_GRANARY_GOD_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_REEF_PARADISE', 'LOC_BELIEF_ZYL_LBM_REEF_PARADISE_NAME', 'LOC_BELIEF_ZYL_LBM_REEF_PARADISE_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_LBM_SIREN', 'LOC_BELIEF_ZYL_LBM_SIREN_NAME', 'LOC_BELIEF_ZYL_LBM_SIREN_DESCRIPTION', 'BELIEF_CLASS_PANTHEON'),
	('BELIEF_ZYL_DRUID', 'LOC_BELIEF_ZYL_DRUID_NAME', 'LOC_BELIEF_ZYL_DRUID_DESCRIPTION', 'BELIEF_CLASS_PANTHEON');

------------------------------------------------------------------------------
-- Plot, resource, district and building requirements
------------------------------------------------------------------------------

-- Moon Goddess and Siren share the same Coast/Ocean test.  Lakes use Coast
-- terrain and therefore qualify without a separate feature check.
INSERT OR IGNORE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
	('ZYL_LBM_PLOT_IS_WATER_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY'),
	('ZYL_LBM_PLOT_HAS_SUN_GOD_RESOURCE_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_LBM_LUXURY_ADJACENT_COMMERCIAL_HUB_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_LBM_CITY_HAS_MONUMENT_OR_OBELISK_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY'),
	('ZYL_LBM_CITY_HAS_GRANARY_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL'),
	('ZYL_LBM_PLOT_HAS_REEF_REQUIREMENTS', 'REQUIREMENTSET_TEST_ALL');

INSERT OR IGNORE INTO Requirements (RequirementId, RequirementType) VALUES
	('ZYL_LBM_REQUIRES_PLOT_TERRAIN_COAST', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
	('ZYL_LBM_REQUIRES_PLOT_TERRAIN_OCEAN', 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES'),
	('ZYL_LBM_REQUIRES_PLOT_HAS_SUN_GOD_RESOURCE', 'REQUIREMENT_PLOT_RESOURCE_TAG_MATCHES'),
	('ZYL_LBM_REQUIRES_LUXURY_RESOURCE', 'REQUIREMENT_PLOT_RESOURCE_CLASS_TYPE_MATCHES'),
	('ZYL_LBM_REQUIRES_ADJACENT_COMMERCIAL_HUB', 'REQUIREMENT_PLOT_ADJACENT_DISTRICT_TYPE_MATCHES'),
	('ZYL_LBM_REQUIRES_CITY_HAS_MONUMENT', 'REQUIREMENT_CITY_HAS_BUILDING'),
	('ZYL_LBM_REQUIRES_CITY_HAS_OLD_GOD_OBELISK', 'REQUIREMENT_CITY_HAS_BUILDING'),
	('ZYL_LBM_REQUIRES_CITY_HAS_GRANARY', 'REQUIREMENT_CITY_HAS_BUILDING'),
	('ZYL_LBM_REQUIRES_PLOT_HAS_REEF', 'REQUIREMENT_PLOT_FEATURE_TYPE_MATCHES');

INSERT OR IGNORE INTO RequirementArguments (RequirementId, Name, Value) VALUES
	('ZYL_LBM_REQUIRES_PLOT_TERRAIN_COAST', 'TerrainType', 'TERRAIN_COAST'),
	('ZYL_LBM_REQUIRES_PLOT_TERRAIN_OCEAN', 'TerrainType', 'TERRAIN_OCEAN'),
	('ZYL_LBM_REQUIRES_PLOT_HAS_SUN_GOD_RESOURCE', 'Tag', 'CLASS_ZYL_LBM_SUN_GOD_FAITH'),
	('ZYL_LBM_REQUIRES_LUXURY_RESOURCE', 'ResourceClassType', 'RESOURCECLASS_LUXURY'),
	('ZYL_LBM_REQUIRES_ADJACENT_COMMERCIAL_HUB', 'DistrictType', 'DISTRICT_COMMERCIAL_HUB'),
	('ZYL_LBM_REQUIRES_ADJACENT_COMMERCIAL_HUB', 'MinRange', 1),
	('ZYL_LBM_REQUIRES_ADJACENT_COMMERCIAL_HUB', 'MaxRange', 1),
	('ZYL_LBM_REQUIRES_CITY_HAS_MONUMENT', 'BuildingType', 'BUILDING_MONUMENT'),
	('ZYL_LBM_REQUIRES_CITY_HAS_OLD_GOD_OBELISK', 'BuildingType', 'BUILDING_OLD_GOD_OBELISK'),
	('ZYL_LBM_REQUIRES_CITY_HAS_GRANARY', 'BuildingType', 'BUILDING_GRANARY'),
	('ZYL_LBM_REQUIRES_PLOT_HAS_REEF', 'FeatureType', 'FEATURE_REEF');

INSERT OR IGNORE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
	('ZYL_LBM_PLOT_IS_WATER_REQUIREMENTS', 'ZYL_LBM_REQUIRES_PLOT_TERRAIN_COAST'),
	('ZYL_LBM_PLOT_IS_WATER_REQUIREMENTS', 'ZYL_LBM_REQUIRES_PLOT_TERRAIN_OCEAN'),
	('ZYL_LBM_PLOT_HAS_SUN_GOD_RESOURCE_REQUIREMENTS', 'ZYL_LBM_REQUIRES_PLOT_HAS_SUN_GOD_RESOURCE'),
	('ZYL_LBM_LUXURY_ADJACENT_COMMERCIAL_HUB_REQUIREMENTS', 'ZYL_LBM_REQUIRES_LUXURY_RESOURCE'),
	('ZYL_LBM_LUXURY_ADJACENT_COMMERCIAL_HUB_REQUIREMENTS', 'ZYL_LBM_REQUIRES_ADJACENT_COMMERCIAL_HUB'),
	('ZYL_LBM_CITY_HAS_MONUMENT_OR_OBELISK_REQUIREMENTS', 'ZYL_LBM_REQUIRES_CITY_HAS_MONUMENT'),
	('ZYL_LBM_CITY_HAS_MONUMENT_OR_OBELISK_REQUIREMENTS', 'ZYL_LBM_REQUIRES_CITY_HAS_OLD_GOD_OBELISK'),
	('ZYL_LBM_CITY_HAS_GRANARY_REQUIREMENTS', 'ZYL_LBM_REQUIRES_CITY_HAS_GRANARY'),
	('ZYL_LBM_PLOT_HAS_REEF_REQUIREMENTS', 'ZYL_LBM_REQUIRES_PLOT_HAS_REEF');

-- Wheat, Rice and Maize qualify when they exist in the active ruleset.
INSERT OR IGNORE INTO Tags (Tag, Vocabulary) VALUES
	('CLASS_ZYL_LBM_SUN_GOD_FAITH', 'RESOURCE_CLASS');

INSERT OR IGNORE INTO TypeTags (Type, Tag)
	SELECT ResourceType, 'CLASS_ZYL_LBM_SUN_GOD_FAITH'
	FROM Resources
	WHERE ResourceType IN ('RESOURCE_WHEAT', 'RESOURCE_RICE', 'RESOURCE_MAIZE');

------------------------------------------------------------------------------
-- Modifiers
------------------------------------------------------------------------------

INSERT OR IGNORE INTO Modifiers
	(ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId)
VALUES
	('ZYL_LBM_MOON_GODDESS_WATER_GOLD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_MOON_GODDESS_WATER_GOLD_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'ZYL_LBM_PLOT_IS_WATER_REQUIREMENTS'),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_CAPACITY', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_CAPACITY_MODIFIER', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', 0, 0, NULL),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH_MODIFIER', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD', 0, 0, NULL),
	('ZYL_LBM_SUN_GOD_RESOURCE_FAITH', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_SUN_GOD_RESOURCE_FAITH_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'ZYL_LBM_PLOT_HAS_SUN_GOD_RESOURCE_REQUIREMENTS'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'PLOT_HAS_PLANTATION_REQUIREMENTS'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'PLOT_HAS_PLANTATION_REQUIREMENTS'),
	('ZYL_LBM_EARTH_SPIRITS_PLOT_PURCHASE_DISCOUNT', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_EARTH_SPIRITS_PLOT_PURCHASE_DISCOUNT_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_PLOT_PURCHASE_COST', 0, 0, NULL),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'PLOT_HAS_PLANTATION_REQUIREMENTS'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'PLOT_HAS_PLANTATION_REQUIREMENTS'),
	('ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK_MODIFIER', 'MODIFIER_ZYL_LBM_PLAYER_ADJUST_DISTRICT_UNLOCK', 0, 0, NULL),
	('ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'ZYL_LBM_LUXURY_ADJACENT_COMMERCIAL_HUB_REQUIREMENTS'),
	('ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION_MODIFIER', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD', 0, 0, NULL),
	('ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT_MODIFIER', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST', 0, 0, NULL),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION_MODIFIER', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 0, 'DISTRICT_IS_ENCAMPMENT'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE_MODIFIER', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 0, 'DISTRICT_IS_ENCAMPMENT'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD', 'MODIFIER_ALL_PLAYERS_ATTACH_MODIFIER', 0, 0, 'PLAYER_HAS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD_MODIFIER', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_CHANGE', 0, 0, 'DISTRICT_IS_ENCAMPMENT'),
	('ZYL_LBM_SACRED_INSCRIPTIONS_FAITH', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_SACRED_INSCRIPTIONS_FAITH_MODIFIER', 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 0, 0, 'ZYL_LBM_CITY_HAS_MONUMENT_OR_OBELISK_REQUIREMENTS'),
	('ZYL_LBM_GRANARY_GOD_CULTURE', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_GRANARY_GOD_CULTURE_MODIFIER', 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 0, 0, 'ZYL_LBM_CITY_HAS_GRANARY_REQUIREMENTS'),
	('ZYL_LBM_GRANARY_GOD_GOLD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_GRANARY_GOD_GOLD_MODIFIER', 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 0, 0, 'ZYL_LBM_CITY_HAS_GRANARY_REQUIREMENTS'),
	('ZYL_LBM_GRANARY_GOD_FAITH', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_GRANARY_GOD_FAITH_MODIFIER', 'MODIFIER_SINGLE_CITY_ADJUST_YIELD_CHANGE', 0, 0, 'ZYL_LBM_CITY_HAS_GRANARY_REQUIREMENTS'),
	('ZYL_LBM_REEF_PARADISE_FOOD', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_REEF_PARADISE_FOOD_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'ZYL_LBM_PLOT_HAS_REEF_REQUIREMENTS'),
	('ZYL_LBM_REEF_PARADISE_CULTURE', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_REEF_PARADISE_CULTURE_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'ZYL_LBM_PLOT_HAS_REEF_REQUIREMENTS'),
	('ZYL_LBM_SIREN_WATER_FAITH', 'MODIFIER_ALL_CITIES_ATTACH_MODIFIER', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS'),
	('ZYL_LBM_SIREN_WATER_FAITH_MODIFIER', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 0, 0, 'ZYL_LBM_PLOT_IS_WATER_REQUIREMENTS'),
	('ZYL_DRUID_WOODS_FAITH_ADJACENCY', 'MODIFIER_ALL_CITIES_FEATURE_ADJACENCY', 0, 0, 'CITY_FOLLOWS_PANTHEON_REQUIREMENTS');

INSERT OR IGNORE INTO ModifierArguments (ModifierId, Name, Value) VALUES
	('ZYL_LBM_MOON_GODDESS_WATER_GOLD', 'ModifierId', 'ZYL_LBM_MOON_GODDESS_WATER_GOLD_MODIFIER'),
	('ZYL_LBM_MOON_GODDESS_WATER_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
	('ZYL_LBM_MOON_GODDESS_WATER_GOLD_MODIFIER', 'Amount', 2),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_CAPACITY', 'ModifierId', 'ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_CAPACITY_MODIFIER'),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_CAPACITY_MODIFIER', 'Amount', 1),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH', 'ModifierId', 'ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH_MODIFIER'),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH_MODIFIER', 'YieldType', 'YIELD_FAITH'),
	('ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH_MODIFIER', 'Amount', 1),
	('ZYL_LBM_SUN_GOD_RESOURCE_FAITH', 'ModifierId', 'ZYL_LBM_SUN_GOD_RESOURCE_FAITH_MODIFIER'),
	('ZYL_LBM_SUN_GOD_RESOURCE_FAITH_MODIFIER', 'YieldType', 'YIELD_FAITH'),
	('ZYL_LBM_SUN_GOD_RESOURCE_FAITH_MODIFIER', 'Amount', 2),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD', 'ModifierId', 'ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD_MODIFIER'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD_MODIFIER', 'YieldType', 'YIELD_FOOD'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD_MODIFIER', 'Amount', 1),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD', 'ModifierId', 'ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD_MODIFIER'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
	('ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD_MODIFIER', 'Amount', 2),
	('ZYL_LBM_EARTH_SPIRITS_PLOT_PURCHASE_DISCOUNT', 'ModifierId', 'ZYL_LBM_EARTH_SPIRITS_PLOT_PURCHASE_DISCOUNT_MODIFIER'),
	('ZYL_LBM_EARTH_SPIRITS_PLOT_PURCHASE_DISCOUNT_MODIFIER', 'Amount', -50),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE', 'ModifierId', 'ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE_MODIFIER'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE_MODIFIER', 'YieldType', 'YIELD_SCIENCE'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE_MODIFIER', 'Amount', 1),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD', 'ModifierId', 'ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD_MODIFIER'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
	('ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD_MODIFIER', 'Amount', 2),
	('ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK', 'ModifierId', 'ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK_MODIFIER'),
	('ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK_MODIFIER', 'DistrictType', 'DISTRICT_COMMERCIAL_HUB'),
	('ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK_MODIFIER', 'TechType', 'TECH_POTTERY'),
	('ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD', 'ModifierId', 'ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD_MODIFIER'),
	('ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
	('ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD_MODIFIER', 'Amount', 2),
	('ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION', 'ModifierId', 'ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION_MODIFIER'),
	('ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION_MODIFIER', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION_MODIFIER', 'Amount', 1),
	('ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT', 'ModifierId', 'ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT_MODIFIER'),
	('ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT_MODIFIER', 'UnitType', 'UNIT_TRADER'),
	('ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT_MODIFIER', 'Amount', 50),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION', 'ModifierId', 'ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION_MODIFIER'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION_MODIFIER', 'YieldType', 'YIELD_PRODUCTION'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION_MODIFIER', 'Amount', 1),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE', 'ModifierId', 'ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE_MODIFIER'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE_MODIFIER', 'YieldType', 'YIELD_CULTURE'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE_MODIFIER', 'Amount', 1),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD', 'ModifierId', 'ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD_MODIFIER'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
	('ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD_MODIFIER', 'Amount', 2),
	('ZYL_LBM_SACRED_INSCRIPTIONS_FAITH', 'ModifierId', 'ZYL_LBM_SACRED_INSCRIPTIONS_FAITH_MODIFIER'),
	('ZYL_LBM_SACRED_INSCRIPTIONS_FAITH_MODIFIER', 'YieldType', 'YIELD_FAITH'),
	('ZYL_LBM_SACRED_INSCRIPTIONS_FAITH_MODIFIER', 'Amount', 3),
	('ZYL_LBM_GRANARY_GOD_CULTURE', 'ModifierId', 'ZYL_LBM_GRANARY_GOD_CULTURE_MODIFIER'),
	('ZYL_LBM_GRANARY_GOD_CULTURE_MODIFIER', 'YieldType', 'YIELD_CULTURE'),
	('ZYL_LBM_GRANARY_GOD_CULTURE_MODIFIER', 'Amount', 1),
	('ZYL_LBM_GRANARY_GOD_GOLD', 'ModifierId', 'ZYL_LBM_GRANARY_GOD_GOLD_MODIFIER'),
	('ZYL_LBM_GRANARY_GOD_GOLD_MODIFIER', 'YieldType', 'YIELD_GOLD'),
	('ZYL_LBM_GRANARY_GOD_GOLD_MODIFIER', 'Amount', 1),
	('ZYL_LBM_GRANARY_GOD_FAITH', 'ModifierId', 'ZYL_LBM_GRANARY_GOD_FAITH_MODIFIER'),
	('ZYL_LBM_GRANARY_GOD_FAITH_MODIFIER', 'YieldType', 'YIELD_FAITH'),
	('ZYL_LBM_GRANARY_GOD_FAITH_MODIFIER', 'Amount', 1),
	('ZYL_LBM_REEF_PARADISE_FOOD', 'ModifierId', 'ZYL_LBM_REEF_PARADISE_FOOD_MODIFIER'),
	('ZYL_LBM_REEF_PARADISE_FOOD_MODIFIER', 'YieldType', 'YIELD_FOOD'),
	('ZYL_LBM_REEF_PARADISE_FOOD_MODIFIER', 'Amount', 1),
	('ZYL_LBM_REEF_PARADISE_CULTURE', 'ModifierId', 'ZYL_LBM_REEF_PARADISE_CULTURE_MODIFIER'),
	('ZYL_LBM_REEF_PARADISE_CULTURE_MODIFIER', 'YieldType', 'YIELD_CULTURE'),
	('ZYL_LBM_REEF_PARADISE_CULTURE_MODIFIER', 'Amount', 1),
	('ZYL_LBM_SIREN_WATER_FAITH', 'ModifierId', 'ZYL_LBM_SIREN_WATER_FAITH_MODIFIER'),
	('ZYL_LBM_SIREN_WATER_FAITH_MODIFIER', 'YieldType', 'YIELD_FAITH'),
	('ZYL_LBM_SIREN_WATER_FAITH_MODIFIER', 'Amount', 1),
	('ZYL_DRUID_WOODS_FAITH_ADJACENCY', 'DistrictType', 'DISTRICT_HOLY_SITE'),
	('ZYL_DRUID_WOODS_FAITH_ADJACENCY', 'FeatureType', 'FEATURE_FOREST'),
	('ZYL_DRUID_WOODS_FAITH_ADJACENCY', 'YieldType', 'YIELD_FAITH'),
	('ZYL_DRUID_WOODS_FAITH_ADJACENCY', 'Amount', 1),
	('ZYL_DRUID_WOODS_FAITH_ADJACENCY', 'Description', 'LOC_DISTRICT_ZYL_DRUID_WOODS_FAITH');

-- Defensive cleanup for databases or saved test fixtures that already loaded
-- the upstream BBG Woods modifier before this ZYL split.
DELETE FROM BeliefModifiers
WHERE BeliefType = 'BELIEF_SACRED_PATH'
  AND ModifierId = 'BBG_SACRED_PATH_WOODS_FAITH_ADJACENCY';

INSERT OR IGNORE INTO BeliefModifiers (BeliefType, ModifierID) VALUES
	('BELIEF_ZYL_LBM_MOON_GODDESS', 'ZYL_LBM_MOON_GODDESS_WATER_GOLD'),
	('BELIEF_ZYL_LBM_COMMERCE_GODDESS', 'ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_CAPACITY'),
	('BELIEF_ZYL_LBM_COMMERCE_GODDESS', 'ZYL_LBM_COMMERCE_GODDESS_TRADE_ROUTE_FAITH'),
	('BELIEF_ZYL_LBM_SUN_GOD', 'ZYL_LBM_SUN_GOD_RESOURCE_FAITH'),
	('BELIEF_ZYL_LBM_ORAL_TRADITION', 'ZYL_LBM_ORAL_TRADITION_PLANTATION_FOOD'),
	('BELIEF_ZYL_LBM_ORAL_TRADITION', 'ZYL_LBM_ORAL_TRADITION_PLANTATION_GOLD'),
	('BELIEF_ZYL_LBM_EARTH_SPIRITS', 'ZYL_LBM_EARTH_SPIRITS_PLOT_PURCHASE_DISCOUNT'),
	('BELIEF_ZYL_LBM_GARDEN_GODDESS', 'ZYL_LBM_GARDEN_GODDESS_PLANTATION_SCIENCE'),
	('BELIEF_ZYL_LBM_GARDEN_GODDESS', 'ZYL_LBM_GARDEN_GODDESS_PLANTATION_GOLD'),
	('BELIEF_ZYL_LBM_WEALTH_GODDESS', 'ZYL_LBM_WEALTH_GODDESS_COMMERCIAL_HUB_UNLOCK'),
	('BELIEF_ZYL_LBM_WEALTH_GODDESS', 'ZYL_LBM_WEALTH_GODDESS_LUXURY_GOLD'),
	('BELIEF_ZYL_LBM_TRADE_GOD', 'ZYL_LBM_TRADE_GOD_ROUTE_PRODUCTION'),
	('BELIEF_ZYL_LBM_TRADE_GOD', 'ZYL_LBM_TRADE_GOD_TRADER_DISCOUNT'),
	('BELIEF_ZYL_LBM_PATH_OF_CONQUEST', 'ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_PRODUCTION'),
	('BELIEF_ZYL_LBM_PATH_OF_CONQUEST', 'ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_CULTURE'),
	('BELIEF_ZYL_LBM_PATH_OF_CONQUEST', 'ZYL_LBM_PATH_OF_CONQUEST_ENCAMPMENT_GOLD'),
	('BELIEF_ZYL_LBM_SACRED_INSCRIPTIONS', 'ZYL_LBM_SACRED_INSCRIPTIONS_FAITH'),
	('BELIEF_ZYL_LBM_GRANARY_GOD', 'ZYL_LBM_GRANARY_GOD_CULTURE'),
	('BELIEF_ZYL_LBM_GRANARY_GOD', 'ZYL_LBM_GRANARY_GOD_GOLD'),
	('BELIEF_ZYL_LBM_GRANARY_GOD', 'ZYL_LBM_GRANARY_GOD_FAITH'),
	('BELIEF_ZYL_LBM_REEF_PARADISE', 'ZYL_LBM_REEF_PARADISE_FOOD'),
	('BELIEF_ZYL_LBM_REEF_PARADISE', 'ZYL_LBM_REEF_PARADISE_CULTURE'),
	('BELIEF_ZYL_LBM_SIREN', 'ZYL_LBM_SIREN_WATER_FAITH'),
	('BELIEF_ZYL_DRUID', 'ZYL_DRUID_WOODS_FAITH_ADJACENCY');
